### ISSUE TITLE
zhihu_user_info_spider报错

### ISSUE THREAD

**Issue by clhne** [srx-2000/spider_collection#42]
**具体项目**
zhihu_user_info_spider

**bug描述**
2023-12-12 15:29:21 - ERROR: 用户回答获取失败,请带着以下报错去github原仓库提出issue
2023-12-12 15:29:21 - ERROR: None
Traceback (most recent call last):
  File "/spider_collection/zhihu_user_info_spider/zhihu_user_info_spider/requester/QuestionRequester.py", line 84, in __get_single_question_user_id
    total_num = self.__get_total(question)
  File "/spider_collection/zhihu_user_info_spider/zhihu_user_info_spider/requester/QuestionRequester.py", line 118, in __get_total
    headers=self._header_with_zse_96(api_url=question_url),
  File "/spider_collection/zhihu_user_info_spider/zhihu_user_info_spider/requester/ModeRequester.py", line 30, in _header_with_zse_96
    header["x-zse-96"] = Parser.get_x_zse_96(api_url)
  File "/spider_collection/zhihu_user_info_spider/zhihu_user_info_spider/parser/Parser.py", line 122, in get_x_zse_96
    cookie_mes = cookie[cookie.index(star):].replace(star, '')
ValueError: substring not found

**bug复现步骤**
1. python spider.py
2. ...

**报错信息**
2023-12-12 15:29:21 - ERROR: 用户回答获取失败,请带着以下报错去github原仓库提出issue
2023-12-12 15:29:21 - ERROR: None
Traceback (most recent call last):
  File "/spider_collection/zhihu_user_info_spider/zhihu_user_info_spider/requester/QuestionRequester.py", line 84, in __get_single_question_user_id
    total_num = self.__get_total(question)
  File "/spider_collection/zhihu_user_info_spider/zhihu_user_info_spider/requester/QuestionRequester.py", line 118, in __get_total
    headers=self._header_with_zse_96(api_url=question_url),
  File "/spider_collection/zhihu_user_info_spider/zhihu_user_info_spider/requester/ModeRequester.py", line 30, in _header_with_zse_96
    header["x-zse-96"] = Parser.get_x_zse_96(api_url)
  File "/spider_collection/zhihu_user_info_spider/zhihu_user_info_spider/parser/Parser.py", line 122, in get_x_zse_96
    cookie_mes = cookie[cookie.index(star):].replace(star, '')
ValueError: substring not found

**系统环境**
 - 操作系统: Linux
 - ide: pycharm
 - pyhon版本: 3.6.9

**其他**
其余相关描述或内容

**Comment by clhne** [comment]
{"error":{"message":"请求参数异常，请升级客户端后重试。","code":10003}}

**Comment by srx-2000** [comment]
> {"error":{"message":"请求参数异常，请升级客户端后重试。","code":10003}}

这个爬虫已经过期了，如果还想爬知乎的话可以看下本项目中的[zhihuEncrypt](https://github.com/srx-2000/spider_collection/tree/dab641a3a45885b1fcb0fb344088111ed13a1a49/zhihuEncrypt)这个加密，这里面有写知乎的加密，具体要爬取什么还请自行编写
